# render.yaml
# Blueprint configuration for the "comparador-precios-app"

services:
  # Este es un servicio temporal solo para inicializar el Blueprint.
  # Lo eliminaremos y reemplazaremos con nuestros scrapers más adelante.
  - type: web
    name: initial-setup
    env: static
    plan: free # Importante para no generar costos
    staticPublishPath: .