# render.yaml
# Blueprint configuration for the "comparador-precios-app"

services:
  # Este es un placeholder de tipo "Sitio Estático" para inicializar el Blueprint.
  # El plan 'starter' es el nivel gratuito actual de Render para este servicio.
  - type: static_site
    name: initial-setup-placeholder
    plan: starter