# render.yaml
# Final Blueprint configuration based on official Render documentation.

services:
  # Defines a static web service placeholder on the free tier.
  - type: web
    name: initial-setup-placeholder
    runtime: static
    plan: free # Explicitly using the 'free' plan as per the docs.
    staticPublishPath: .