# render.yaml
# Configuración actualizada para usar Docker.

services:
  - type: cron
    name: santa-isabel-scraper
    runtime: docker # <-- ¡Cambiamos a Docker!
    plan: free
    schedule: "0 8 * * *"
    
    # Configuración de Docker
    dockerfilePath: ./scrapers/Dockerfile # Ruta a nuestro Dockerfile
    dockerContext: ./scrapers # Carpeta donde se ejecuta la construcción
    
    # El comando se ejecuta dentro del contenedor ya construido
    startCommand: "python scrape_santaisabel.py"
    
    envVars:
      - fromGroup: supabase-credentials
