# render.yaml
# Blueprint configuration following the official Render spec.

services:
  # Define a static web service placeholder.
  # This is the modern way to define a static site on Render.
  - type: web
    name: initial-setup-placeholder
    env: static
    plan: Free # The official name for the free tier on web services.
    staticPublishPath: . # Serve content from the root directory.